
import {
  ArrowRight,
  Brain,
  CheckCircle,
  LogIn,
  Sparkles,
  Target,
  TrendingUp,
  UserPlus,
} from "lucide-react";
import { Link } from "react-router-dom";

export default function LandingPage() {
  const features = [
    {
      icon: Brain,
      title: "AI Study Plans",
      description:
        "Generate personalized study roadmaps based on your goals and experience.",
    },
    {
      icon: TrendingUp,
      title: "Track Progress",
      description:
        "Complete daily tasks and monitor your learning progress visually.",
    },
    {
      icon: Target,
      title: "AI Interviews",
      description:
        "Practice realistic coding and theory interviews generated by AI.",
    },
    {
      icon: CheckCircle,
      title: "AI Feedback",
      description:
        "Receive detailed scores, strengths and improvement suggestions.",
    },
    {
      icon: Brain,
      title: "Interview History",
      description:
        "Resume unfinished interviews and review previous performance.",
    },
    {
      icon: Sparkles,
      title: "Voice Answers",
      description:
        "Answer interview questions using voice with automatic transcription.",
    },
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-violet-50 via-white to-indigo-50">
      <header className="sticky top-0 z-50 border-b border-violet-100 bg-white/80 backdrop-blur">
        <div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4">
          <div className="flex items-center gap-3">
            <div className="relative flex h-11 w-11 items-center justify-center rounded-2xl bg-gradient-to-br from-violet-600 to-indigo-600 shadow-lg">
              <Target className="absolute h-8 w-8 text-violet-300/40" />
              <Brain className="relative h-5 w-5 text-white" />
            </div>

            <div>
              <h1 className="text-lg font-bold text-gray-900">
                FocusFlow
              </h1>
              <p className="text-xs text-gray-500">
                AI Learning Platform
              </p>
            </div>
          </div>

          <div className="flex gap-3">
            <Link to="/login">
              <button className="flex items-center gap-2 rounded-lg px-4 py-2 text-gray-700 hover:bg-gray-100">
                <LogIn size={16} />
                Login
              </button>
            </Link>

            <Link to="/register">
              <button className="flex items-center gap-2 rounded-xl bg-violet-600 px-5 py-2 text-white hover:bg-violet-700">
                <UserPlus size={16} />
                Sign Up
              </button>
            </Link>
          </div>
        </div>
      </header>

      <section className="mx-auto max-w-6xl px-6 py-24 text-center">
        <div className="inline-flex items-center gap-2 rounded-full bg-violet-100 px-4 py-2 text-sm font-medium text-violet-700">
          <Sparkles size={15} />
          AI Powered Study Platform
        </div>

        <h1 className="mt-8 text-5xl font-extrabold leading-tight text-gray-900">
          Learn Smarter.
          <br />
          <span className="bg-gradient-to-r from-violet-600 to-indigo-600 bg-clip-text text-transparent">
            Crack Interviews Faster.
          </span>
        </h1>

        <p className="mx-auto mt-6 max-w-2xl text-lg text-gray-600">
          FocusFlow creates personalized study plans, tracks your progress,
          generates AI mock interviews, and helps you improve with intelligent
          feedback.
        </p>

        <div className="mt-10 flex flex-wrap justify-center gap-4">
          <Link to="/register">
            <button className="flex items-center gap-2 rounded-xl bg-violet-600 px-7 py-3 font-semibold text-white hover:bg-violet-700">
              Get Started
              <ArrowRight size={18} />
            </button>
          </Link>

          <Link to="/login">
            <button className="rounded-xl border border-violet-200 px-7 py-3 font-semibold text-violet-700 hover:bg-violet-50">
              Login
            </button>
          </Link>
        </div>
      </section>

      <section className="mx-auto max-w-6xl px-6 pb-24">
        <h2 className="mb-10 text-center text-3xl font-bold text-gray-900">
          Everything You Need
        </h2>

        <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
          {features.map((feature) => {
            const Icon = feature.icon;

            return (
              <div
                key={feature.title}
                className="rounded-2xl border border-violet-100 bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:shadow-lg"
              >
                <div className="mb-4 flex h-12 w-12 items-center justify-center rounded-xl bg-violet-100">
                  <Icon className="text-violet-600" size={22} />
                </div>

                <h3 className="font-semibold text-gray-900">
                  {feature.title}
                </h3>

                <p className="mt-3 text-sm leading-6 text-gray-600">
                  {feature.description}
                </p>
              </div>
            );
          })}
        </div>
      </section>

      <section className="mx-auto max-w-6xl px-6 pb-24">
        <div className="rounded-3xl bg-gradient-to-r from-violet-600 to-indigo-600 p-10 text-center text-white">
          <h2 className="text-3xl font-bold">
            How FocusFlow Works
          </h2>

          <div className="mt-10 grid gap-8 md:grid-cols-4">
            <div>
              <div className="text-3xl font-bold">1</div>
              <p className="mt-2">Create a Study Plan</p>
            </div>

            <div>
              <div className="text-3xl font-bold">2</div>
              <p className="mt-2">Complete Daily Tasks</p>
            </div>

            <div>
              <div className="text-3xl font-bold">3</div>
              <p className="mt-2">Take AI Interviews</p>
            </div>

            <div>
              <div className="text-3xl font-bold">4</div>
              <p className="mt-2">Improve with AI Feedback</p>
            </div>
          </div>
        </div>
      </section>

      <section className="pb-20 text-center">
        <h2 className="text-3xl font-bold text-gray-900">
          Ready to Start Learning?
        </h2>

        <p className="mx-auto mt-4 max-w-xl text-gray-600">
          Join FocusFlow and prepare for your next technical interview with AI.
        </p>

        <Link to="/register">
          <button className="mt-8 rounded-xl bg-violet-600 px-8 py-3 font-semibold text-white hover:bg-violet-700">
            Get Started Free
          </button>
        </Link>
      </section>

      <footer className="border-t border-violet-100 py-6 text-center text-sm text-gray-500">
        © 2026 FocusFlow • AI Study Planner & Interview Preparation
      </footer>
    </div>
  );
}
